apiVersion: v1
kind: Pod
metadata:
  name: ns1
  labels:
    app: communicate-app
  namespace: surya
spec:
  restartPolicy: Always
  containers:
    - name: nginx1
      image: nginx
      ports:
        - containerPort: 80
