apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  namespace: surya
  labels:
   env: dev
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30005
  selector:
    env: test
    type: nginx
