apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels: 
    env: test
    type: nginx
spec:
  template:
    metadata:
      labels: 
        env: test
        type: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
           - containerPort: 80
  replicas: 2        