apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: surya-naginx
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: my-nginx
          image: nginx:latest