apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
   environment: dev
   type: forntend
spec:
  containers:
    - name: my-nginx
      image: nginx:latest
      ports:
       - containerPort: 90