apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    env: prod
  namespace: surya
spec:
  containers:
    - name: my-app-env
      image: busybox:1.28
      env:
        - name: FIRSTNAME
          valueFrom:
            configMapKeyRef:
              name: test-cm
              key: firstname
      command: ['sh', '-c', 'echo The app is running! && sleep 3600']
      ports:
        - containerPort: 80
