apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: surya
data:
  app.properties: |
    APP_ENV=production
    APP_DEBUG=false
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-pod
  namespace: surya
spec:
  containers:
    - name: app-container
      image: busybox
      command: ["/bin/sh", "-c", "cat /etc/config/app.properties && sleep 3600"]
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
          readOnly: true
  volumes:
    - name: config-volume
      configMap:
        name: app-config
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: surya
type: Opaque
data:
  username: bXlfdXNlcm5hbWU= # Base64-encoded value of 'my_username'
  password: bXlfcGFzc3dvcmQ= # Base64-encoded value of 'my_password'

# echo -n "my_username" | base64 echo -n "my_password" | base64
---

---
apiVersion: v1
kind: Pod
metadata:
  name: combined-volume-pod
  namespace: surya
spec:
  containers:
    - name: app-container
      image: busybox
      command: ["/bin/sh", "-c", "ls /etc/config && ls /etc/secrets && sleep 3600"]
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
          readOnly: true
        - name: secret-volume
          mountPath: /etc/secrets
          readOnly: true
  volumes:
    - name: config-volume
      configMap:
        name: app-config
    - name: secret-volume
      secret:
        secretName: db-credentials
