apiVersion: v1
kind: Pod
metadata:
  name: my-ld
  namespace: surya
  labels: 
    env: test
    type: nginx
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      ports:
       - containerPort: 80
         