apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: surya
subjects:
  - kind: User
    name: surya
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
