apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app # This matches the label on the Pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
