apiVersion: v1
kind: Pod
metadata:
  name: my-noaffinity
  labels:
    name: new-affinity
    env: demo
  namespace: surya
spec:
  containers:
    - name: my-noaffinity
      image: nginx
      ports:
        - containerPort: 80
  restartPolicy: Always
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "disktype"
                operator: "Exists"
