apiVersion: v1
kind: Pod
metadata:
  name: my-affinity
  labels:
    name: new-affinity
    env: demo
  namespace: surya
spec:
  containers:
    - name: my-affinity
      image: nginx
      ports:
        - containerPort: 80
  restartPolicy: Always
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disktype
                operator: In
                values:
                  - ssd
